zad4/Models/Product.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Resources;

namespace zad4.Models
{
    public class Product
    {
        [Display(Name = "Id")]
        public int id { get; set; }
        [Display(Name = "Nazwa")]
        [Required(ErrorMessage = "Nazwa jest wymagana.")]
        public string name { get; set; }
        [Display(Name = "Cena")]
        [Required(ErrorMessage = "Cena jest wymagana.")]
        [Range(0.01, double.MaxValue, ErrorMessage ="Cena musi być większa od 0")]
        public decimal price { get; set; }
        public Product() {}
        public Product(int id, string name, decimal price)
        {
            this.id = id;
            this.name = name;
            this.price = price;
        }
        public static List<Product> GetProducts()
        {
            Product pilka = new Product { id = 1, name = "Piłka nożna", price = 25.30M };
            Product narty = new Product { id = 2, name = "Narty", price = 150.39M };
            Product rakieta = new Product { id = 3, name = "Rakieta ", price = 111.10M };

            return new List<Product> { pilka, narty, rakieta };
        }
        public override string ToString() 
        {
            return "Id: "+id.ToString()+" Nazwa: "+name.ToString()+" Cena: "+price.ToString();
        }
    }

}

zad4/Pages/Basket/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using zad4.Models;
using System.Text.Json;
using zad4.DAL;
using System.Reflection;


namespace zad4.Pages.Basket
{
    public class IndexModel : MyPageModel
    {
        public BasketModel koszyk = null;
        public List<Product> productList;
        public void OnGet()
        {
            var koszykJson = Request.Cookies["Koszyk"];
            if (!string.IsNullOrEmpty(koszykJson))
                koszyk = JsonSerializer.Deserialize<BasketModel>(koszykJson, ProductDictionaryKeyConverter.jsonSerializeConventorOptions);

            LoadDB();
            productList = productDB.List();
        }

        public IActionResult OnGetAddToBasket(int id) 
        {
            LoadDB();
            Product product = productDB.getProduct(id);
            koszyk = new BasketModel();
            var koszykJson = Request.Cookies["Koszyk"];
            if (!string.IsNullOrEmpty(koszykJson))
                koszyk = JsonSerializer.Deserialize<BasketModel>(koszykJson, ProductDictionaryKeyConverter.jsonSerializeConventorOptions);
            Product existedProduct = null;
            foreach (var item in koszyk.Products)
                if (item.Key.name == product.name && item.Key.price == product.price && item.Key.id == product.id)
                    existedProduct = item.Key;
            if (existedProduct != null)
                koszyk.Products[existedProduct] = koszyk.Products[existedProduct] + 1;
            else
                koszyk.Products.Add(product, 1);
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(1)
            };
            Response.Cookies.Append("Koszyk", JsonSerializer.Serialize(koszyk, ProductDictionaryKeyConverter.jsonSerializeConventorOptions), cookieOptions);
            return RedirectToPage();
        }

        public IActionResult OnGetAddToBasketReturnToPreviousPage(int id)
        {
            LoadDB();
            Product product = productDB.getProduct(id);
            koszyk = new BasketModel();
            var koszykJson = Request.Cookies["Koszyk"];
            if (!string.IsNullOrEmpty(koszykJson))
                koszyk = JsonSerializer.Deserialize<BasketModel>(koszykJson, ProductDictionaryKeyConverter.jsonSerializeConventorOptions);
            Product existedProduct = null;
            foreach (var item in koszyk.Products)
                if (item.Key.name == product.name && item.Key.price == product.price && item.Key.id == product.id)
                    existedProduct = item.Key;
            if (existedProduct != null)
                koszyk.Products[existedProduct] = koszyk.Products[existedProduct] + 1;
            else
                koszyk.Products.Add(product, 1);
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(1)
            };
            Response.Cookies.Append("Koszyk", JsonSerializer.Serialize(koszyk, ProductDictionaryKeyConverter.jsonSerializeConventorOptions), cookieOptions);
            string url = Request.Headers["Referer"].ToString();
            return Redirect(url);
        }

        public IActionResult OnPostClearBasket()
        {
            var koszyk = new BasketModel();
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(1)
            };
            Response.Cookies.Append("Koszyk", JsonSerializer.Serialize(koszyk, ProductDictionaryKeyConverter.jsonSerializeConventorOptions), cookieOptions);
            return RedirectToPage();
        }

        public IActionResult OnPostDeleteBasket()
        {
            var koszyk = new BasketModel();
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(-1)
            };
            Response.Cookies.Append("Koszyk", JsonSerializer.Serialize(koszyk, ProductDictionaryKeyConverter.jsonSerializeConventorOptions), cookieOptions);
            return RedirectToPage();
        }

        public IActionResult OnPostDeleteNotAvailableProducts(string basketJSON, string productsJSON) 
        {
            productList = JsonSerializer.Deserialize<List<Product>>(productsJSON, ProductDictionaryKeyConverter.jsonSerializeConventorOptions);
            koszyk = JsonSerializer.Deserialize<BasketModel>(basketJSON, ProductDictionaryKeyConverter.jsonSerializeConventorOptions);
            if (koszyk is null) return RedirectToPage();

            foreach (var item in koszyk.Products)
            {
                if (!productList.Any(p => (p.name == item.Key.name && p.price == item.Key.price)))
                {
                    Console.WriteLine("POWINNO USUNAC: "+item.Key);
                    koszyk.Products.Remove(item.Key);
                }
            }
            Console.WriteLine(koszyk);
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(1)
            };
            Response.Cookies.Append("Koszyk", JsonSerializer.Serialize(koszyk, ProductDictionaryKeyConverter.jsonSerializeConventorOptions), cookieOptions);
            return RedirectToPage();
        }
    }
}

zad4/Pages/List.cshtml.cs
using System.Collections.Generic;
using zad4.Models;

namespace zad4.Pages
{
    public class ListModel : MyPageModel
    {
        public List<Product> productList;
        public void OnGet()
        {
            LoadDB();
            productList = productDB.List();
            SaveDB();
        }
    }
}

zad4/Pages/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Reflection;
using zad4.Models;

namespace zad4.Pages.Products
{
    public class DeleteModel : MyPageModel
    {
        [BindProperty]
        public Product newProduct { get; set; }
        public void OnGet(int id)
        {
            LoadDB();
            newProduct = productDB.getProduct(id);
        }
        public IActionResult OnPost()
        {
            LoadDB();
            productDB.Delete(newProduct.id);
            SaveDB();
            return RedirectToPage("List");
        }
    }
}

zad4/Pages/Products/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using zad4.DAL;
using zad4.Models;

namespace zad4.Pages.Products
{
    public class DetailsModel : MyPageModel
    {
        public Product newProduct { get; set; }
        public void OnGet(int id)
        {
            LoadDB();
            newProduct = productDB.getProduct(id);
            TempData["idProductu"] = id.ToString();
        }

        public IActionResult OnPost()
        {
            int idProductu = int.Parse(TempData["idProductu"] as string);
            return RedirectToPage("./../Basket/Index", "AddToBasket", new {id = idProductu});
        }
    }
}

zad4/Pages/Products/List.cshtml.cs
using System.Collections.Generic;
using zad4.Models;

namespace zad4.Pages.Products
{
    public class ListModel : MyPageModel
    {
        public List<Product> productList;
        public void OnGet()
        {
            LoadDB();
            productList = productDB.List();
            SaveDB();
        }
    }
}

zad4/Pages/Products/Create.cshtml
@page
@model zad4.Pages.Products.CreateModel
@{
    ViewData["Title"] = "Nowy produkt";
}
<h2>Nowy produkt</h2>
<br /><br />
<div class="container">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label asp-for="newProduct.name" class="control-label col-sm-2"></label>
            <div class="col-sm-6">
                <input asp-for="newProduct.name" class="form-control" placeholder="nazwa produktu">
                <span asp-validation-for="newProduct.name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="newProduct.price" class="control-label col-sm-2"></label>
            <div class="col-sm-6">
                <input asp-for="newProduct.price" class="form-control" placeholder="cena">
                <span asp-validation-for="newProduct.price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary">Zatwierdź</button>
                <a asp-page="./List" class="btn btn-danger">Anuluj dodawanie produktu</a>
            </div>
        </div>
    </form>
</div>

zad4/Pages/Products/Delete.cshtml
@page
@model zad4.Pages.Products.DeleteModel
@{
}
<h2>Nowy produkt</h2>
<br /><br />
<div class="container">
    <form class="form-horizontal" method="post">
        <input type="hidden" asp-for="newProduct.id" />
        <div class="form-group">
            <label asp-for="newProduct.name" class="control-label col-sm-2"></label> @Model.newProduct.name
        </div>
        <div class="form-group">
            <label asp-for="newProduct.price" class="control-label col-sm-2"></label> @Model.newProduct.price
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-danger">Usun produkt</button>
                <a asp-page="./List" class="btn btn-primary">Wróć do listy</a>
            </div>
        </div>
    </form>
</div>

zad4/Pages/Products/Details.cshtml
@page
@model zad4.Pages.Products.DetailsModel
@{
}
<h2>Szczegóły</h2>
<br /><br />
<div class="container">
    <div class="form-group">
        <label asp-for="newProduct.id" class="control-label col-sm-2"></label> @Model.newProduct.id
    </div>
    <div class="form-group">
        <label asp-for="newProduct.name" class="control-label col-sm-2"></label> @Model.newProduct.name
    </div>
    <div class="form-group">
        <label asp-for="newProduct.price" class="control-label col-sm-2"></label> @Model.newProduct.price
    </div>
    <form class="form-horizontal" method="post">
        <button class="btn btn-primary">Dodaj do koszyka</button>
    </form>
    <a asp-page="./List">Wróć do listy</a>
</div>

zad4/Pages/Products/Edit.cshtml
@page
@model zad4.Pages.Products.EditModel
@{
}
<h2>Edytuj produkt</h2>
<br /><br />
<div class="container">
    <form class="form-horizontal" method="post">
        <input type="hidden" asp-for="newProduct.id" />
        <div class="form-group">
            <label asp-for="newProduct.name" class="control-label col-sm-2"></label>
            <div class="col-sm-6">
                <input asp-for="newProduct.name" class="form-control">
                <span asp-validation-for="newProduct.name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="newProduct.price" class="control-label col-sm-2"></label>
            <div class="col-sm-6">
                <input asp-for="newProduct.price" class="form-control">
                <span asp-validation-for="newProduct.price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn btn-primary">Zatwierdź</button>
                <a asp-page="./List" class="btn btn-danger">Wróć do listy bez zmian</a>
            </div>
        </div>
    </form>
</div>

zad4/Pages/Products/List.cshtml
@page
@model ListModel
@{
    ViewData["Title"] = "Lista produktów";
}
<h2>Lista produktów</h2>
<div class="row col-sm-12">
<a asp-page="Create" class="btn btn-primary btn-large">Dodaj</a>
</div>
<br /><br />
<table class="table table-striped">
    <thead>
    <tr>
    <th scope="col">@Html.DisplayNameFor(model =>
    Model.productList[0].id)</th>
    <th scope="col">@Html.DisplayNameFor(model =>
    Model.productList[0].name)</th>
    <th scope="col">@Html.DisplayNameFor(model =>
    Model.productList[0].price)</th>
    <th scope="col">Akcja</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var p in Model.productList)
        {
            <tr>
                <th scope="row">@Html.DisplayFor(m => p.id)</th>
                <td>@Html.DisplayFor(m => p.name)</td>
                <td>@Html.DisplayFor(m => p.price)</td>
                <td>
                    <a asp-page="Details" asp-route-id=@p.id>Szczegóły</a> |
                    <a asp-page="Edit" asp-route-id=@p.id>Edytuj</a> |
                    <a asp-page="Delete" asp-route-id=@p.id>Kasuj</a> |
                    <a asp-page="./../Basket/Index" asp-page-handler="AddToBasketReturnToPreviousPage" asp-route-id="@p.id">Dodaj do koszyka</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-page="./../Basket/Index" class="btn btn-primary" style="float:right">Przejdź do koszyka</a>